//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;



namespace cfg
{ 
public partial class Tables
{
    public Battle.TBGLConst TBGLConst {get; }
    public Battle.TBGameEnvItem TBGameEnvItem {get; }
    public Battle.TBSheepInfo TBSheepInfo {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TBGLConst = new Battle.TBGLConst(loader("battle_tbglconst")); 
        tables.Add("Battle.TBGLConst", TBGLConst);
        TBGameEnvItem = new Battle.TBGameEnvItem(loader("battle_tbgameenvitem")); 
        tables.Add("Battle.TBGameEnvItem", TBGameEnvItem);
        TBSheepInfo = new Battle.TBSheepInfo(loader("battle_tbsheepinfo")); 
        tables.Add("Battle.TBSheepInfo", TBSheepInfo);

        PostInit();
        TBGLConst.Resolve(tables); 
        TBGameEnvItem.Resolve(tables); 
        TBSheepInfo.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TBGLConst.TranslateText(translator); 
        TBGameEnvItem.TranslateText(translator); 
        TBSheepInfo.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}