//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.Battle
{ 
    /// <summary>
    /// 游戏环境物体
    /// </summary>
    [System.Flags]
    public enum EEnvItem
    {
        /// <summary>
        /// 草丛
        /// </summary>
        Grass = 10001,
        /// <summary>
        /// 花
        /// </summary>
        Flower = 10002,
        /// <summary>
        /// 云
        /// </summary>
        WhiteCloud = 10003,
        /// <summary>
        /// 雨云
        /// </summary>
        RainCloud = 10004,
        /// <summary>
        /// 雷雨云
        /// </summary>
        ThunderCloud = 10005,
        /// <summary>
        /// 水坑
        /// </summary>
        Puddle = 10006,
        /// <summary>
        /// 圣女果
        /// </summary>
        Fruit = 10007,
        /// <summary>
        /// 毒蘑菇
        /// </summary>
        Agaric = 10008,
    }

} 
