//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.Battle
{ 
    /// <summary>
    /// 获取方式
    /// </summary>
    [System.Flags]
    public enum EGetWay
    {
        /// <summary>
        /// 无
        /// </summary>
        None = -1,
        /// <summary>
        /// 免费道具
        /// </summary>
        Free = 0,
        /// <summary>
        /// 付费道具1
        /// </summary>
        gift1 = 1,
        /// <summary>
        /// 付费道具2
        /// </summary>
        gift2 = 2,
        /// <summary>
        /// 付费道具3
        /// </summary>
        gift3 = 3,
        /// <summary>
        /// 付费道具4
        /// </summary>
        gift4 = 4,
        /// <summary>
        /// 付费道具5
        /// </summary>
        gift5 = 5,
        /// <summary>
        /// 付费道具6
        /// </summary>
        gift6 = 6,
    }

} 
