//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.Battle
{ 

public sealed partial class GameEnvItem :  Bright.Config.BeanBase 
{
    public GameEnvItem(JSONNode _json) 
    {
        { if(!_json["Id"].IsNumber) { throw new SerializationException(); }  Id = _json["Id"]; }
        { if(!_json["Name"].IsString) { throw new SerializationException(); }  Name = _json["Name"]; }
        { var __json0 = _json["Hp"]; if(!__json0.IsArray) { throw new SerializationException(); } Hp = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Hp.Add(__v0); }   }
        { if(!_json["MaxCount"].IsNumber) { throw new SerializationException(); }  MaxCount = _json["MaxCount"]; }
        { if(!_json["RefreshInv"].IsNumber) { throw new SerializationException(); }  RefreshInv = _json["RefreshInv"]; }
        { if(!_json["GenerateItem"].IsNumber) { throw new SerializationException(); }  GenerateItem = _json["GenerateItem"]; }
        PostInit();
    }

    public GameEnvItem(int Id, string Name, System.Collections.Generic.List<int> Hp, int MaxCount, int RefreshInv, int GenerateItem ) 
    {
        this.Id = Id;
        this.Name = Name;
        this.Hp = Hp;
        this.MaxCount = MaxCount;
        this.RefreshInv = RefreshInv;
        this.GenerateItem = GenerateItem;
        PostInit();
    }

    public static GameEnvItem DeserializeGameEnvItem(JSONNode _json)
    {
        return new Battle.GameEnvItem(_json);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 单位名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 血量
    /// </summary>
    public System.Collections.Generic.List<int> Hp { get; private set; }
    /// <summary>
    /// 最多个数
    /// </summary>
    public int MaxCount { get; private set; }
    /// <summary>
    /// 刷新速度
    /// </summary>
    public int RefreshInv { get; private set; }
    /// <summary>
    /// 转化物体
    /// </summary>
    public int GenerateItem { get; private set; }

    public const int __ID__ = -313743080;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Hp:" + Bright.Common.StringUtil.CollectionToString(Hp) + ","
        + "MaxCount:" + MaxCount + ","
        + "RefreshInv:" + RefreshInv + ","
        + "GenerateItem:" + GenerateItem + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
