//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.Battle
{ 

public sealed partial class SheepInfo :  Bright.Config.BeanBase 
{
    public SheepInfo(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  Name = _json["name"]; }
        { if(!_json["moveSpeed"].IsNumber) { throw new SerializationException(); }  MoveSpeed = _json["moveSpeed"]; }
        { if(!_json["attackRange"].IsNumber) { throw new SerializationException(); }  AttackRange = _json["attackRange"]; }
        { if(!_json["attackInv"].IsNumber) { throw new SerializationException(); }  AttackInv = _json["attackInv"]; }
        { if(!_json["attack"].IsNumber) { throw new SerializationException(); }  Attack = _json["attack"]; }
        PostInit();
    }

    public SheepInfo(int id, string name, float moveSpeed, float attackRange, float attackInv, int attack ) 
    {
        this.Id = id;
        this.Name = name;
        this.MoveSpeed = moveSpeed;
        this.AttackRange = attackRange;
        this.AttackInv = attackInv;
        this.Attack = attack;
        PostInit();
    }

    public static SheepInfo DeserializeSheepInfo(JSONNode _json)
    {
        return new Battle.SheepInfo(_json);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 单位名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 移动速度
    /// </summary>
    public float MoveSpeed { get; private set; }
    /// <summary>
    /// 攻击范围
    /// </summary>
    public float AttackRange { get; private set; }
    /// <summary>
    /// 吃果子间隔
    /// </summary>
    public float AttackInv { get; private set; }
    /// <summary>
    /// 伤害
    /// </summary>
    public int Attack { get; private set; }

    public const int __ID__ = 1495372531;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "MoveSpeed:" + MoveSpeed + ","
        + "AttackRange:" + AttackRange + ","
        + "AttackInv:" + AttackInv + ","
        + "Attack:" + Attack + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
