//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Battle
{
public sealed partial class GameEnvItem :  Bright.Config.BeanBase 
{
    public GameEnvItem(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Hp = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Hp.Add(_e0);}}
        MaxCount = _buf.ReadInt();
        RefreshInv = _buf.ReadInt();
        GenerateItem = _buf.ReadInt();
        PostInit();
    }

    public static GameEnvItem DeserializeGameEnvItem(ByteBuf _buf)
    {
        return new Battle.GameEnvItem(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 单位名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 血量
    /// </summary>
    public System.Collections.Generic.List<int> Hp { get; private set; }
    /// <summary>
    /// 最多个数
    /// </summary>
    public int MaxCount { get; private set; }
    /// <summary>
    /// 刷新速度
    /// </summary>
    public int RefreshInv { get; private set; }
    /// <summary>
    /// 转化物体
    /// </summary>
    public int GenerateItem { get; private set; }

    public const int __ID__ = -313743080;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Hp:" + Bright.Common.StringUtil.CollectionToString(Hp) + ","
        + "MaxCount:" + MaxCount + ","
        + "RefreshInv:" + RefreshInv + ","
        + "GenerateItem:" + GenerateItem + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}