//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.Battle
{ 

public sealed partial class GLConst :  Bright.Config.BeanBase 
{
    public GLConst(JSONNode _json) 
    {
        { if(!_json["MaxPlayerCount"].IsNumber) { throw new SerializationException(); }  MaxPlayerCount = _json["MaxPlayerCount"]; }
        { if(!_json["SheepNormalSpeed"].IsNumber) { throw new SerializationException(); }  SheepNormalSpeed = _json["SheepNormalSpeed"]; }
        { if(!_json["SheepUpSpeed"].IsNumber) { throw new SerializationException(); }  SheepUpSpeed = _json["SheepUpSpeed"]; }
        { if(!_json["SheepFlySpeed"].IsNumber) { throw new SerializationException(); }  SheepFlySpeed = _json["SheepFlySpeed"]; }
        { if(!_json["WhiteCloudSpeed"].IsNumber) { throw new SerializationException(); }  WhiteCloudSpeed = _json["WhiteCloudSpeed"]; }
        { if(!_json["RainCloudSpeed"].IsNumber) { throw new SerializationException(); }  RainCloudSpeed = _json["RainCloudSpeed"]; }
        { if(!_json["ThunderCloudSpeed"].IsNumber) { throw new SerializationException(); }  ThunderCloudSpeed = _json["ThunderCloudSpeed"]; }
        { if(!_json["FlashIntervalTime"].IsNumber) { throw new SerializationException(); }  FlashIntervalTime = _json["FlashIntervalTime"]; }
        { if(!_json["SuperGift1Count"].IsNumber) { throw new SerializationException(); }  SuperGift1Count = _json["SuperGift1Count"]; }
        { if(!_json["SuperGift2Count"].IsNumber) { throw new SerializationException(); }  SuperGift2Count = _json["SuperGift2Count"]; }
        { if(!_json["SuperGift3Count"].IsNumber) { throw new SerializationException(); }  SuperGift3Count = _json["SuperGift3Count"]; }
        { if(!_json["SuperGift4Count"].IsNumber) { throw new SerializationException(); }  SuperGift4Count = _json["SuperGift4Count"]; }
        { if(!_json["SuperGift5Count"].IsNumber) { throw new SerializationException(); }  SuperGift5Count = _json["SuperGift5Count"]; }
        { if(!_json["SuperGift6Count"].IsNumber) { throw new SerializationException(); }  SuperGift6Count = _json["SuperGift6Count"]; }
        { if(!_json["PerMaxLittleSheepCount"].IsNumber) { throw new SerializationException(); }  PerMaxLittleSheepCount = _json["PerMaxLittleSheepCount"]; }
        { if(!_json["VertigoBossTime"].IsNumber) { throw new SerializationException(); }  VertigoBossTime = _json["VertigoBossTime"]; }
        { if(!_json["VertigoSheepTime"].IsNumber) { throw new SerializationException(); }  VertigoSheepTime = _json["VertigoSheepTime"]; }
        PostInit();
    }

    public GLConst(int MaxPlayerCount, float SheepNormalSpeed, float SheepUpSpeed, float SheepFlySpeed, float WhiteCloudSpeed, float RainCloudSpeed, float ThunderCloudSpeed, float FlashIntervalTime, int SuperGift1Count, int SuperGift2Count, int SuperGift3Count, int SuperGift4Count, int SuperGift5Count, int SuperGift6Count, int PerMaxLittleSheepCount, float VertigoBossTime, float VertigoSheepTime ) 
    {
        this.MaxPlayerCount = MaxPlayerCount;
        this.SheepNormalSpeed = SheepNormalSpeed;
        this.SheepUpSpeed = SheepUpSpeed;
        this.SheepFlySpeed = SheepFlySpeed;
        this.WhiteCloudSpeed = WhiteCloudSpeed;
        this.RainCloudSpeed = RainCloudSpeed;
        this.ThunderCloudSpeed = ThunderCloudSpeed;
        this.FlashIntervalTime = FlashIntervalTime;
        this.SuperGift1Count = SuperGift1Count;
        this.SuperGift2Count = SuperGift2Count;
        this.SuperGift3Count = SuperGift3Count;
        this.SuperGift4Count = SuperGift4Count;
        this.SuperGift5Count = SuperGift5Count;
        this.SuperGift6Count = SuperGift6Count;
        this.PerMaxLittleSheepCount = PerMaxLittleSheepCount;
        this.VertigoBossTime = VertigoBossTime;
        this.VertigoSheepTime = VertigoSheepTime;
        PostInit();
    }

    public static GLConst DeserializeGLConst(JSONNode _json)
    {
        return new Battle.GLConst(_json);
    }

    /// <summary>
    /// 最大玩家数量
    /// </summary>
    public int MaxPlayerCount { get; private set; }
    /// <summary>
    /// 未点赞羊群速度
    /// </summary>
    public float SheepNormalSpeed { get; private set; }
    /// <summary>
    /// 点赞羊群速度
    /// </summary>
    public float SheepUpSpeed { get; private set; }
    /// <summary>
    /// 飞天羊群
    /// </summary>
    public float SheepFlySpeed { get; private set; }
    /// <summary>
    /// 白云速度
    /// </summary>
    public float WhiteCloudSpeed { get; private set; }
    /// <summary>
    /// 雨云速度
    /// </summary>
    public float RainCloudSpeed { get; private set; }
    /// <summary>
    /// 雷雨云速度
    /// </summary>
    public float ThunderCloudSpeed { get; private set; }
    /// <summary>
    /// 打雷间隔时间
    /// </summary>
    public float FlashIntervalTime { get; private set; }
    /// <summary>
    /// 大礼物1数量
    /// </summary>
    public int SuperGift1Count { get; private set; }
    /// <summary>
    /// 大礼物2数量
    /// </summary>
    public int SuperGift2Count { get; private set; }
    /// <summary>
    /// 大礼物3数量
    /// </summary>
    public int SuperGift3Count { get; private set; }
    /// <summary>
    /// 大礼物4数量
    /// </summary>
    public int SuperGift4Count { get; private set; }
    /// <summary>
    /// 大礼物5数量
    /// </summary>
    public int SuperGift5Count { get; private set; }
    /// <summary>
    /// 大礼物6数量
    /// </summary>
    public int SuperGift6Count { get; private set; }
    /// <summary>
    /// 单位最大小羊个数
    /// </summary>
    public int PerMaxLittleSheepCount { get; private set; }
    /// <summary>
    /// 眩晕boss时间/秒
    /// </summary>
    public float VertigoBossTime { get; private set; }
    /// <summary>
    /// 眩晕羊时间/秒
    /// </summary>
    public float VertigoSheepTime { get; private set; }

    public const int __ID__ = -120325528;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "MaxPlayerCount:" + MaxPlayerCount + ","
        + "SheepNormalSpeed:" + SheepNormalSpeed + ","
        + "SheepUpSpeed:" + SheepUpSpeed + ","
        + "SheepFlySpeed:" + SheepFlySpeed + ","
        + "WhiteCloudSpeed:" + WhiteCloudSpeed + ","
        + "RainCloudSpeed:" + RainCloudSpeed + ","
        + "ThunderCloudSpeed:" + ThunderCloudSpeed + ","
        + "FlashIntervalTime:" + FlashIntervalTime + ","
        + "SuperGift1Count:" + SuperGift1Count + ","
        + "SuperGift2Count:" + SuperGift2Count + ","
        + "SuperGift3Count:" + SuperGift3Count + ","
        + "SuperGift4Count:" + SuperGift4Count + ","
        + "SuperGift5Count:" + SuperGift5Count + ","
        + "SuperGift6Count:" + SuperGift6Count + ","
        + "PerMaxLittleSheepCount:" + PerMaxLittleSheepCount + ","
        + "VertigoBossTime:" + VertigoBossTime + ","
        + "VertigoSheepTime:" + VertigoSheepTime + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
