//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Battle
{
public sealed partial class SheepInfo :  Bright.Config.BeanBase 
{
    public SheepInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        MoveSpeed = _buf.ReadFloat();
        AttackRange = _buf.ReadFloat();
        AttackInv = _buf.ReadFloat();
        Attack = _buf.ReadInt();
        PostInit();
    }

    public static SheepInfo DeserializeSheepInfo(ByteBuf _buf)
    {
        return new Battle.SheepInfo(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 单位名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 移动速度
    /// </summary>
    public float MoveSpeed { get; private set; }
    /// <summary>
    /// 攻击范围
    /// </summary>
    public float AttackRange { get; private set; }
    /// <summary>
    /// 吃果子间隔
    /// </summary>
    public float AttackInv { get; private set; }
    /// <summary>
    /// 伤害
    /// </summary>
    public int Attack { get; private set; }

    public const int __ID__ = 1495372531;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "MoveSpeed:" + MoveSpeed + ","
        + "AttackRange:" + AttackRange + ","
        + "AttackInv:" + AttackInv + ","
        + "Attack:" + Attack + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}